## Land acknowledgement {background-image=assets/img/land_ack.jpg background-size=cover background-opacity="0.4"}

**I would like to acknowledge that I work on the traditional, ancestral, and unceded territory of the Coast Salish Peoples, including the territories of the xwməθkwəy̓əm (Musqueam), Skwxwú7mesh (Squamish), Stó:lō and Səl̓ílwətaʔ/Selilwitulh (Tsleil- Waututh) Nations.**

*Traditional*: Traditionally used and/or occupied by Musqueam people

*Ancestral*: Recognizes land that is handed down from generation to generation

*Unceded*: Refers to land that was not turned over to the Crown (government) by a treaty or other agreement

::: {.notes}

* Be short on this slide
* Traditional, ancestral, unceded territory of Coast Salish people, inckuding territories of :
  * Musqueam
  * Squamish
  * Tsleil-Waututh Nations

:::

## Background Heart Transplant

## Background Heart Rejection

## Background ACR vs Quilty

## Background Types of data

## Background In-house data

- Cite collaborators
- Or have their names and pic in here

## Background what method to apply

- Need to know which method is most suitable to apply on this
- Which there really isnt any after the pipeline run

## MESSI pipeline

- Overview pic of the pipeline

## MESSI component cleaning

## MESSI component evaluation

## MESSI results on sim data

## MESSI results on real data

## MESSI future direction

## Current work on GeoMX

## Background of GeoMX

## GeoMx results 1

## GeoMx results 2

## GeoMx results 3

## GeoMx results 4

## Next steps

## Conclusion

## Acknowledgments

## Reference